import { Providers } from "./providers";

export const metadata = {
  title: "Login | FINDEB FZCO Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <Providers>{children}</Providers>;
}
